name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
   

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
      id: go

    - name: check out code into Go module directory
      uses: actions/setup-go@v4

    - name: Test
      run: make test
